### ISSUE TITLE
java.lang.ClassCastException: java.util.concurrent.ConcurrentLinkedQueue

### ISSUE THREAD

**Issue by mibby** [mbax/TagAPI#11]
Spigot 1350 (upstream merged with CraftBukkit 3030 1.7.5.)
TagAPI dev 141.

```
[03:37:16] [Server thread/WARN]: java.lang.ClassCastException: java.util.concurrent.ConcurrentLinkedQueue cannot be cast to net.minecraft.util.io.netty.channel.Channel
[03:37:16] [Server thread/WARN]:    at org.kitteh.tag.api.PacketHandlerNetty.getPipeline(PacketHandlerNetty.java:60)
[03:37:16] [Server thread/WARN]:    at org.kitteh.tag.api.PacketHandlerNetty.hookPlayer(PacketHandlerNetty.java:70)
[03:37:16] [Server thread/WARN]:    at org.kitteh.tag.api.PacketHandlerBase$HandlerListener.onPlayerJoin(PacketHandlerBase.java:37)
[03:37:16] [Server thread/WARN]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03:37:16] [Server thread/WARN]:    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[03:37:16] [Server thread/WARN]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[03:37:16] [Server thread/WARN]:    at java.lang.reflect.Method.invoke(Unknown Source)
[03:37:16] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292)
[03:37:16] [Server thread/WARN]:    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[03:37:16] [Server thread/WARN]:    at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30)
[03:37:16] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[03:37:16] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[03:37:16] [Server thread/WARN]:    at net.minecraft.server.v1_7_R2.PlayerList.c(PlayerList.java:249)
[03:37:16] [Server thread/WARN]:    at net.minecraft.server.v1_7_R2.PlayerList.a(PlayerList.java:135)
[03:37:16] [Server thread/WARN]:    at net.minecraft.server.v1_7_R2.LoginListener.c(LoginListener.java:87)
[03:37:16] [Server thread/WARN]:    at net.minecraft.server.v1_7_R2.LoginListener.a(LoginListener.java:42)
[03:37:16] [Server thread/WARN]:    at net.minecraft.server.v1_7_R2.NetworkManager.a(NetworkManager.java:151)
[03:37:16] [Server thread/WARN]:    at net.minecraft.server.v1_7_R2.ServerConnection.c(ServerConnection.java:77)
[03:37:16] [Server thread/WARN]:    at net.minecraft.server.v1_7_R2.MinecraftServer.v(MinecraftServer.java:703)
[03:37:16] [Server thread/WARN]:    at net.minecraft.server.v1_7_R2.DedicatedServer.v(DedicatedServer.java:273)
[03:37:16] [Server thread/WARN]:    at net.minecraft.server.v1_7_R2.MinecraftServer.u(MinecraftServer.java:566)
[03:37:16] [Server thread/WARN]:    at net.minecraft.server.v1_7_R2.MinecraftServer.run(MinecraftServer.java:472)
[03:37:16] [Server thread/WARN]:    at net.minecraft.server.v1_7_R2.ThreadServerApplication.run(SourceFile:618)
```

**Comment by mbax** [comment]
Ohhhhhhhhh bother.

**Comment by mibby** [comment]
I should note, it occurs every single time a player logs in.

**Comment by mbax** [comment]
It will. Grab 3.0.2
